---
functional:
  - Возможность авторизации с помощью своего аккаунта на Github 
  - Возможность авторизации с помощью email и пароля 
  - Победителем должен являться тот, кто верно решил задачу и затратил на это меньше времени 
  - Возможность выбора языка программирования в терминале баттла 
  - Возможность настраивать параметры игры; сложность, выбор оппонента, лимит времени, тип задания 
  - Возможность создать поединок с другим пользователем/другом/ботом 
  - Возможность проматривать статистику по поединкам, чемпионатам и игрокам 
  - Возможность дописать код и/или ознакомиться с кодом соперника после завершения батла 
  - Возможность организации турниров и турнирной сетки 
  - Возможность переподключения участника к баттлу 
  - Возможность сортировки таблицы лидеров по рейтингу, количеству игр и т.д 
  - Возможность отправлять приглашение на баттл другим пользователям 
  - Возможность просмотра истории баттлов 
  - Возможность просмотра повтора баттла 
  - Возможность находиться только в одном баттле одновременно 
  - Реализация функции сдаться, сброса кода, проверки решения в терминале 
  - Реализация мультиязычности 
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь удобную мобильную версию
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен обладать удобной интуитивно понятной и быстрой регистрацией 
  - Сайт должен быть совместим с последними версиями распространенных браузеров
implicit:
  - Участник не может писать и изменять в терминал соперника
  - Зрители не могут писать код и вносить изменения в терминалах участников
  - Реализована возможность просмотра игроков online 
  - Участники не могут вносить изменения в предустановленную задачу баттла 
