---
functional:
  - Возможность авторизации через Github
  - Ведение рейтинга игроков по неделе/месяцу/всего и отображение на главной странице. Возможность сортировки по рейтингу, количеству игр и т.д.
  - Возможность просмотра истории баттлов.
  - Возможность просмотра повтора баттла.
  - Возможность кастомизации при создании лобби - сложность, задача, теги и временной лимит
  - Возможность выбора языка программирования в терминале баттла
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Участник не может писать и изменять код соперника
  - Зрители не могут писать код и вносить изменения в код участников
  - Пользователи не могут вносить изменения в таблицу лидеров вручную
  - Участники не могут вносить изменения в предустановленную задачу баттла
